#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <limits.h>
#include <poll.h>
#include <sys/inotify.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <errno.h>

/*
 * inotify_demo.c — Demonstrate Linux inotify filesystem event watching.
 *
 * Kernel path:
 *   inotify_add_watch(2) -> sys_inotify_add_watch() -> inotify_update_watch()
 *   https://elixir.bootlin.com/linux/v6.9/source/fs/notify/inotify/inotify_user.c
 *
 *   Events generated by fsnotify_parent() in fs/notify/fsnotify.c:
 *   https://elixir.bootlin.com/linux/v6.9/source/fs/notify/fsnotify.c
 *
 * struct inotify_event:
 *   https://elixir.bootlin.com/linux/v6.9/source/include/uapi/linux/inotify.h
 */

#define EVENT_BUF_LEN (10 * (sizeof(struct inotify_event) + NAME_MAX + 1))

/* Decode an inotify event mask into a human-readable string. */
static const char *decode_mask(uint32_t mask, char *buf, size_t len)
{
    buf[0] = '\0';
    if (mask & IN_CREATE)      strncat(buf, "CREATE|",      len - strlen(buf) - 1);
    if (mask & IN_MODIFY)      strncat(buf, "MODIFY|",      len - strlen(buf) - 1);
    if (mask & IN_DELETE)      strncat(buf, "DELETE|",      len - strlen(buf) - 1);
    if (mask & IN_MOVED_FROM)  strncat(buf, "MOVED_FROM|",  len - strlen(buf) - 1);
    if (mask & IN_MOVED_TO)    strncat(buf, "MOVED_TO|",    len - strlen(buf) - 1);
    if (mask & IN_CLOSE_WRITE) strncat(buf, "CLOSE_WRITE|", len - strlen(buf) - 1);
    if (mask & IN_ISDIR)       strncat(buf, "ISDIR|",       len - strlen(buf) - 1);
    if (mask & IN_IGNORED)     strncat(buf, "IGNORED|",     len - strlen(buf) - 1);
    /* trim trailing '|' */
    size_t l = strlen(buf);
    if (l > 0 && buf[l - 1] == '|')
        buf[l - 1] = '\0';
    return buf;
}

/* Child: performs a sequence of file operations to generate inotify events. */
static void child_work(const char *dir)
{
    char path1[PATH_MAX];
    char path2[PATH_MAX];
    char path_tsec[PATH_MAX];
    char path_sec[PATH_MAX];
    int fd;
    ssize_t written;

    /* 1. Create file1.txt, write "hello", close. */
    snprintf(path1, sizeof(path1), "%s/file1.txt", dir);
    fd = open(path1, O_WRONLY | O_CREAT | O_TRUNC, 0644);
    if (fd < 0) { perror("open file1.txt"); exit(1); }
    written = write(fd, "hello", 5);
    if (written < 0) { perror("write file1.txt"); exit(1); }
    close(fd);
    usleep(100000);

    /* 2. Open file1.txt for append, write " world", close. */
    fd = open(path1, O_WRONLY | O_APPEND);
    if (fd < 0) { perror("open file1.txt append"); exit(1); }
    written = write(fd, " world", 6);
    if (written < 0) { perror("write append"); exit(1); }
    close(fd);
    usleep(100000);

    /* 3. Rename file1.txt -> file2.txt (MOVED_FROM + MOVED_TO, same cookie). */
    snprintf(path2, sizeof(path2), "%s/file2.txt", dir);
    if (rename(path1, path2) < 0) { perror("rename file1->file2"); exit(1); }
    usleep(100000);

    /* 4. Create tmp_secret.txt, write "password", close.
     *    Simulate the atomic secret write pattern used by Kubernetes:
     *    write to a temp file, then atomically rename into place. */
    snprintf(path_tsec, sizeof(path_tsec), "%s/tmp_secret.txt", dir);
    fd = open(path_tsec, O_WRONLY | O_CREAT | O_TRUNC, 0600);
    if (fd < 0) { perror("open tmp_secret.txt"); exit(1); }
    written = write(fd, "password", 8);
    if (written < 0) { perror("write tmp_secret.txt"); exit(1); }
    close(fd);
    usleep(100000);

    /* 5. Rename tmp_secret.txt -> secret.txt (atomic replace). */
    snprintf(path_sec, sizeof(path_sec), "%s/secret.txt", dir);
    if (rename(path_tsec, path_sec) < 0) { perror("rename tmp_secret->secret"); exit(1); }
    usleep(100000);

    /* 6. Unlink file2.txt. */
    if (unlink(path2) < 0) { perror("unlink file2.txt"); exit(1); }
    usleep(100000);

    /* 7. Unlink secret.txt. */
    if (unlink(path_sec) < 0) { perror("unlink secret.txt"); exit(1); }

    exit(0);
}

int main(void)
{
    char dir[] = "/tmp/inotify-demo-XXXXXX";
    char mask_buf[256];
    char event_buf[EVENT_BUF_LEN];
    int ifd;
    int wd;
    pid_t child;
    int child_done = 0;

    /* Create temporary directory. */
    if (mkdtemp(dir) == NULL) {
        perror("mkdtemp");
        return 1;
    }
    printf("Watching directory: %s\n\n", dir);

    /* Set up inotify. */
    ifd = inotify_init();
    if (ifd < 0) {
        perror("inotify_init");
        rmdir(dir);
        return 1;
    }

    wd = inotify_add_watch(ifd, dir,
                           IN_CREATE | IN_MODIFY | IN_DELETE |
                           IN_MOVED_FROM | IN_MOVED_TO | IN_CLOSE_WRITE);
    if (wd < 0) {
        perror("inotify_add_watch");
        close(ifd);
        rmdir(dir);
        return 1;
    }

    /* Fork child. */
    child = fork();
    if (child < 0) {
        perror("fork");
        close(ifd);
        rmdir(dir);
        return 1;
    }
    if (child == 0) {
        /* Child process: close inotify fd, then do file operations. */
        close(ifd);
        child_work(dir);
        /* child_work() calls exit(), never returns */
    }

    /* Parent: event loop. */
    printf("%-10s %-12s %-10s %s\n", "mask", "events", "cookie", "name");
    printf("%-10s %-12s %-10s %s\n",
           "----------", "------------", "----------", "----");

    while (!child_done) {
        struct pollfd pfd;
        int poll_ret;
        ssize_t len;
        char *ptr;

        pfd.fd = ifd;
        pfd.events = POLLIN;
        pfd.revents = 0;

        /* Wait up to 200ms for events. */
        poll_ret = poll(&pfd, 1, 200);
        if (poll_ret < 0) {
            if (errno == EINTR)
                continue;
            perror("poll");
            break;
        }

        if (poll_ret == 0) {
            /* Timeout — check if child has exited. */
            if (waitpid(child, NULL, WNOHANG) > 0)
                child_done = 1;
            continue;
        }

        /* Data available — read events. */
        len = read(ifd, event_buf, sizeof(event_buf));
        if (len < 0) {
            if (errno == EINTR)
                continue;
            perror("read inotify");
            break;
        }
        if (len == 0)
            break;

        /* Iterate over all events in the buffer. */
        ptr = event_buf;
        while (ptr < event_buf + len) {
            struct inotify_event *ev = (struct inotify_event *)ptr;
            const char *name = (ev->len > 0) ? ev->name : "(none)";

            printf("inotify: mask=0x%08x (%s) cookie=%u name=%s\n",
                   ev->mask,
                   decode_mask(ev->mask, mask_buf, sizeof(mask_buf)),
                   ev->cookie,
                   name);

            ptr += sizeof(struct inotify_event) + ev->len;
        }
    }

    /* Drain any remaining events after child exit. */
    if (child_done) {
        struct pollfd pfd;
        pfd.fd = ifd;
        pfd.events = POLLIN;
        pfd.revents = 0;
        while (poll(&pfd, 1, 50) > 0) {
            ssize_t len = read(ifd, event_buf, sizeof(event_buf));
            if (len <= 0)
                break;
            char *ptr = event_buf;
            while (ptr < event_buf + len) {
                struct inotify_event *ev = (struct inotify_event *)ptr;
                const char *name = (ev->len > 0) ? ev->name : "(none)";
                printf("inotify: mask=0x%08x (%s) cookie=%u name=%s\n",
                       ev->mask,
                       decode_mask(ev->mask, mask_buf, sizeof(mask_buf)),
                       ev->cookie,
                       name);
                ptr += sizeof(struct inotify_event) + ev->len;
            }
            pfd.revents = 0;
        }
    } else {
        /* child_done was set to 0 but loop exited — reap child. */
        waitpid(child, NULL, 0);
    }

    inotify_rm_watch(ifd, wd);
    close(ifd);
    rmdir(dir);
    printf("\nDone. Temp directory removed.\n");
    return 0;
}
